"use client";

import * as React from "react";
import { Save } from "lucide-react";
import { toast } from "sonner";

import { PageHeader } from "@/components/admin/shared/page-header";
import { TimezoneSelect } from "@/components/admin/shared/timezone-select";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

function SettingSwitch({ label, description, defaultChecked = true }: { label: string; description: string; defaultChecked?: boolean }) {
  return <div className="flex items-center justify-between gap-4 py-3"><div><Label>{label}</Label><p className="mt-1 text-xs text-text-secondary">{description}</p></div><Switch defaultChecked={defaultChecked} /></div>;
}

function SaveSettings() { return <div className="flex justify-end"><Button onClick={() => toast.success("Settings saved")}><Save /> Save Settings</Button></div>; }

export function SettingsPage() {
  const [timezone, setTimezone] = React.useState("Africa/Nairobi"); const [dateFormat, setDateFormat] = React.useState("DD/MM/YYYY"); const [closing, setClosing] = React.useState("24 hours before");
  return <div className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6"><PageHeader title="Settings" description="Configure platform defaults, communication and appearance." /><Tabs defaultValue="general"><TabsList className="h-auto flex-wrap"><TabsTrigger value="general">General</TabsTrigger><TabsTrigger value="events">Event Settings</TabsTrigger><TabsTrigger value="email">Email Settings</TabsTrigger><TabsTrigger value="notifications">Notifications</TabsTrigger><TabsTrigger value="appearance">Appearance</TabsTrigger></TabsList>
    <TabsContent value="general" className="mt-4"><Card className="shadow-none"><CardHeader><CardTitle>General settings</CardTitle><CardDescription>Basic platform and regional information.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="platform-name">Platform name</Label><Input id="platform-name" defaultValue="Evently" /></div><div className="space-y-2"><Label htmlFor="contact-email">Contact email</Label><Input id="contact-email" type="email" defaultValue="support@evently.ug" /></div><div className="space-y-2"><Label htmlFor="contact-phone">Contact phone</Label><Input id="contact-phone" defaultValue="+256 700 000 000" /></div><div className="space-y-2"><Label>Default timezone</Label><TimezoneSelect value={timezone} onValueChange={setTimezone} /></div><div className="space-y-2"><Label>Date format</Label><Select value={dateFormat} onValueChange={setDateFormat}><SelectTrigger className="w-full"><SelectValue /></SelectTrigger><SelectContent>{["DD/MM/YYYY", "MM/DD/YYYY", "YYYY-MM-DD"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="sm:col-span-2"><SaveSettings /></div></CardContent></Card></TabsContent>
    <TabsContent value="events" className="mt-4"><Card className="shadow-none"><CardHeader><CardTitle>Event settings</CardTitle><CardDescription>Default registration behavior for newly created events.</CardDescription></CardHeader><CardContent><div className="space-y-2"><Label>Registration closes</Label><Select value={closing} onValueChange={setClosing}><SelectTrigger className="w-full sm:w-64"><SelectValue /></SelectTrigger><SelectContent>{["At event start", "24 hours before", "48 hours before", "7 days before"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><Separator className="my-4" /><SettingSwitch label="Allow public event registration" description="Visitors can register without an administrator invitation." /><Separator /><SettingSwitch label="Allow attendee cancellation" description="Attendees can cancel before registration closes." /><Separator /><SettingSwitch label="Auto-confirm registrations" description="Confirm valid registrations without manual review." /><div className="mt-4"><SaveSettings /></div></CardContent></Card></TabsContent>
    <TabsContent value="email" className="mt-4"><Card className="shadow-none"><CardHeader><CardTitle>Email settings</CardTitle><CardDescription>Public sender information only. SMTP credentials belong on the backend.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="sender-name">Sender name</Label><Input id="sender-name" defaultValue="Evently Events" /></div><div className="space-y-2"><Label htmlFor="sender-email">Sender email</Label><Input id="sender-email" type="email" defaultValue="events@evently.ug" /></div><SaveSettings /></CardContent></Card></TabsContent>
    <TabsContent value="notifications" className="mt-4"><Card className="shadow-none"><CardHeader><CardTitle>Notification settings</CardTitle><CardDescription>Choose which administrative updates are surfaced.</CardDescription></CardHeader><CardContent><SettingSwitch label="Registration notifications" description="Notify admins about new registrations." /><Separator /><SettingSwitch label="Event reminders" description="Send reminders for upcoming platform events." /><Separator /><SettingSwitch label="Organizer alerts" description="Notify when organizers require review." /><Separator /><SettingSwitch label="System alerts" description="Receive security and platform notices." /><div className="mt-4"><SaveSettings /></div></CardContent></Card></TabsContent>
    <TabsContent value="appearance" className="mt-4"><Card className="shadow-none"><CardHeader><CardTitle>Appearance</CardTitle><CardDescription>The theme switch in the top navigation controls light, dark and system modes.</CardDescription></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-lg border border-border bg-[#0F172A] p-4 text-white"><p className="text-sm font-semibold">Navy</p><p className="mt-1 text-xs text-slate-300">#0F172A</p></div><div className="rounded-lg border border-border bg-[#2563EB] p-4 text-white"><p className="text-sm font-semibold">Primary Blue</p><p className="mt-1 text-xs text-blue-100">#2563EB</p></div><div className="rounded-lg border border-border bg-[#F59E0B] p-4 text-[#111827]"><p className="text-sm font-semibold">Amber</p><p className="mt-1 text-xs">#F59E0B</p></div></div><p className="mt-4 text-sm text-text-secondary">Plus Jakarta Sans · Current Evently design system</p></CardContent></Card></TabsContent>
  </Tabs></div>;
}
