import type { RequestHandler } from "express";
import { databaseErrorCode } from "../../config/database";
import * as service from "../../services/organizer/organizer.service";
import { createSetupToken, sendInvitationEmail } from "../../services/invitation.service";
import { optionalText,positiveId,positiveInteger,text } from "../../utils/request";

export const eventStatuses=new Set(["Draft","Upcoming","Active","Completed","Cancelled"]),registrationStatuses=new Set(["Confirmed","Pending","Cancelled"]),speakerTypes=new Set(["Speaker","Guest"]),invitationStatuses=new Set(["Confirmed","Pending"]),agendaTypes=new Set(["None","File","Url"]);
const organizer=(response:any)=>response.locals.organizer as {userId:number;organizerId:number};
const fail=(response:any,error:unknown,action:string)=>{console.error(`${action} failed (${databaseErrorCode(error)})`);const duplicate=typeof error==="object"&&error!==null&&"code" in error&&error.code==="ER_DUP_ENTRY";response.status(duplicate?409:500).json({success:false,message:duplicate?"A record with those unique details already exists":`Unable to ${action.toLowerCase()}`});};
export function eventInput(body:any):service.EventInput|null{const name=text(body?.name),venueId=positiveInteger(body?.venueId),date=text(body?.date),capacity=positiveInteger(body?.capacity),status=text(body?.status),timezone=text(body?.timezone)||"Africa/Nairobi",startTime=optionalText(body?.startTime),endTime=optionalText(body?.endTime),registrationClosesAt=optionalText(body?.registrationClosesAt),agendaType=text(body?.agendaType)||"None";if(!name||!venueId||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!capacity||!eventStatuses.has(status)||!agendaTypes.has(agendaType))return null;if(startTime&&endTime&&endTime<=startTime)return null;if(registrationClosesAt&&registrationClosesAt.slice(0,10)>date)return null;const agendaUrl=agendaType==="None"?null:optionalText(body?.agendaUrl);if(agendaType!=="None"&&!agendaUrl)return null;return{name,venueId,date,capacity,status,timezone,startTime,endTime,registrationClosesAt,theme:optionalText(body?.theme),description:optionalText(body?.description),imageUrl:optionalText(body?.imageUrl),imageAlt:optionalText(body?.imageAlt),agendaType,agendaUrl,agendaFileName:agendaType==="File"?optionalText(body?.agendaFileName):null,agendaFileType:agendaType==="File"?optionalText(body?.agendaFileType):null};}
export function scheduleInput(body:any):service.ScheduleInput|null{const eventId=positiveInteger(body?.eventId),title=text(body?.title),date=text(body?.date),startTime=text(body?.startTime),endTime=optionalText(body?.endTime),speakerId=body?.speakerId?positiveInteger(body.speakerId):null;if(!eventId||!title||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}/.test(startTime)||endTime&&endTime<=startTime)return null;return{eventId,title,date,startTime,endTime,speakerId,description:optionalText(body?.description),room:optionalText(body?.room),sortOrder:Number.isInteger(Number(body?.sortOrder))?Math.max(0,Number(body.sortOrder)):0};}
function speakerInput(body:any):service.SpeakerInput|null{const eventId=positiveInteger(body?.eventId),firstName=text(body?.firstName),email=text(body?.email).toLowerCase(),title=text(body?.title),type=text(body?.type),status=text(body?.status);if(!eventId||!firstName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!title||!speakerTypes.has(type)||!invitationStatuses.has(status))return null;return{eventId,firstName,lastName:optionalText(body?.lastName),email,title,type,status,telephone:optionalText(body?.telephone),organization:optionalText(body?.organization),bio:optionalText(body?.bio),photoUrl:optionalText(body?.photoUrl)};}
export const getDashboard:RequestHandler=async(_req,res)=>{try{res.json({success:true,data:await service.dashboard(organizer(res).organizerId)});}catch(e){fail(res,e,"Load dashboard");}};
export const getTrends:RequestHandler=async(req,res)=>{const days={"7d":7,"30d":30,"90d":90}[String(req.query.range)]??30;try{res.json({success:true,data:await service.registrationTrends(organizer(res).organizerId,days)});}catch(e){fail(res,e,"Load registration trends");}};
export const listEvents:RequestHandler=async(_req,res)=>{try{res.json({success:true,data:await service.listEvents(organizer(res).organizerId)});}catch(e){fail(res,e,"List events");}};
export const getEvent:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id);if(!id){res.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const data=await service.getEvent(organizer(res).organizerId,id);if(!data){res.status(404).json({success:false,message:"Event not found"});return;}res.json({success:true,data});}catch(e){fail(res,e,"Load event");}};
export const createEvent:RequestHandler=async(req,res)=>{const input=eventInput(req.body);if(!input){res.status(400).json({success:false,message:"Valid title, venue, date, capacity, status, and time range are required"});return;}try{const id=await service.createEvent(organizer(res).organizerId,input);res.status(201).json({success:true,message:"Event created successfully",data:{id}});}catch(e){fail(res,e,"Create event");}};
export const updateEvent:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),input=eventInput(req.body);if(!id||!input){res.status(400).json({success:false,message:"Valid event details are required"});return;}try{if(!(await service.updateEvent(organizer(res).organizerId,id,input))){res.status(404).json({success:false,message:"Event not found"});return;}res.json({success:true,message:"Event updated successfully"});}catch(e){fail(res,e,"Update event");}};
export const cancelEvent:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id);if(!id){res.status(400).json({success:false,message:"Valid event ID is required"});return;}try{if(!(await service.cancelEvent(organizer(res).organizerId,id))){res.status(404).json({success:false,message:"Event not found"});return;}res.json({success:true,message:"Event cancelled"});}catch(e){fail(res,e,"Cancel event");}};
export const listRegistrations:RequestHandler=async(req,res)=>{const eventId=req.query.eventId?(positiveInteger(req.query.eventId)??undefined):undefined;if(req.query.eventId&&!eventId){res.status(400).json({success:false,message:"Valid event ID is required"});return;}try{res.json({success:true,data:await service.listRegistrations(organizer(res).organizerId,eventId)});}catch(e){fail(res,e,"List registrations");}};
export const updateRegistration:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),status=text(req.body?.status);if(!id||!registrationStatuses.has(status)){res.status(400).json({success:false,message:"Valid registration status is required"});return;}try{if(!(await service.updateRegistrationStatus(organizer(res).organizerId,id,status))){res.status(404).json({success:false,message:"Registration not found"});return;}res.json({success:true,message:"Registration updated"});}catch(e){fail(res,e,"Update registration");}};
export const checkIn:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),checkedIn=req.body?.checkedIn!==false;if(!id){res.status(400).json({success:false,message:"Valid registration ID is required"});return;}try{if(!(await service.checkInRegistration(organizer(res).organizerId,organizer(res).userId,id,checkedIn))){res.status(404).json({success:false,message:"Registration not found"});return;}res.json({success:true,message:checkedIn?"Attendee checked in":"Check-in removed"});}catch(e){fail(res,e,"Update check-in");}};
export const listAttendees:RequestHandler=async(req,res)=>{const eventId=req.query.eventId?(positiveInteger(req.query.eventId)??undefined):undefined;try{res.json({success:true,data:await service.listAttendees(organizer(res).organizerId,eventId)});}catch(e){fail(res,e,"List attendees");}};
export const listSchedule:RequestHandler=async(req,res)=>{const eventId=req.query.eventId?(positiveInteger(req.query.eventId)??undefined):undefined;try{res.json({success:true,data:await service.listSchedule(organizer(res).organizerId,eventId)});}catch(e){fail(res,e,"List schedule");}};
export const createSchedule:RequestHandler=async(req,res)=>{const input=scheduleInput(req.body);if(!input){res.status(400).json({success:false,message:"Valid event, title, date, and time range are required"});return;}try{const id=await service.createSchedule(organizer(res).organizerId,input);if(!id){res.status(404).json({success:false,message:"Event not found"});return;}res.status(201).json({success:true,message:"Schedule item created",data:{id}});}catch(e){if(e instanceof Error&&e.message==="SPEAKER_NOT_ASSIGNED"){res.status(400).json({success:false,message:"Speaker must be assigned to the selected event"});return;}fail(res,e,"Create schedule item");}};
export const updateSchedule:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),input=scheduleInput(req.body);if(!id||!input){res.status(400).json({success:false,message:"Valid schedule details are required"});return;}try{if(!(await service.updateSchedule(organizer(res).organizerId,id,input))){res.status(404).json({success:false,message:"Schedule item not found"});return;}res.json({success:true,message:"Schedule item updated"});}catch(e){fail(res,e,"Update schedule item");}};
export const deleteSchedule:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id);if(!id){res.status(400).json({success:false,message:"Valid schedule item ID is required"});return;}try{if(!(await service.deleteSchedule(organizer(res).organizerId,id))){res.status(404).json({success:false,message:"Schedule item not found"});return;}res.json({success:true,message:"Schedule item removed"});}catch(e){fail(res,e,"Remove schedule item");}};
export const listSpeakers:RequestHandler=async(req,res)=>{const eventId=req.query.eventId?(positiveInteger(req.query.eventId)??undefined):undefined;try{res.json({success:true,data:await service.listSpeakers(organizer(res).organizerId,eventId)});}catch(e){fail(res,e,"List speakers");}};
export const createSpeaker:RequestHandler=async(req,res)=>{const input=speakerInput(req.body);if(!input){res.status(400).json({success:false,message:"Valid event, speaker identity, type, title, email, and status are required"});return;}try{const id=await service.createSpeaker(organizer(res).organizerId,input);if(!id){res.status(404).json({success:false,message:"Event not found"});return;}res.status(201).json({success:true,message:`${input.type} added`,data:{id}});}catch(e){fail(res,e,"Add speaker or guest");}};
export const updateSpeaker:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),input=speakerInput(req.body);if(!id||!input){res.status(400).json({success:false,message:"Valid speaker details are required"});return;}try{if(!(await service.updateSpeaker(organizer(res).organizerId,id,input))){res.status(404).json({success:false,message:"Speaker assignment not found"});return;}res.json({success:true,message:"Speaker updated"});}catch(e){fail(res,e,"Update speaker");}};
export const deleteSpeaker:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),eventId=positiveInteger(req.query.eventId);if(!id||!eventId){res.status(400).json({success:false,message:"Valid speaker and event IDs are required"});return;}try{if(!(await service.deleteSpeaker(organizer(res).organizerId,eventId,id))){res.status(404).json({success:false,message:"Speaker assignment not found"});return;}res.json({success:true,message:"Speaker removed from event"});}catch(e){fail(res,e,"Remove speaker");}};
export const listStaffOptions:RequestHandler=async(_req,res)=>{try{res.json({success:true,data:await service.listStaffOptions()});}catch(e){fail(res,e,"List staff");}};
export const inviteStaff:RequestHandler=async(req,res)=>{
  const firstName=text(req.body?.firstName),lastName=optionalText(req.body?.lastName),email=text(req.body?.email).toLowerCase(),telephone=optionalText(req.body?.telephone);
  if(!firstName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){res.status(400).json({success:false,message:"First name and a valid email are required"});return;}
  const o=organizer(res);
  try{
    const userId=await service.inviteStaff(o.userId,{firstName,lastName,email,telephone});
    const token=await createSetupToken(userId,o.userId);
    try{
      await sendInvitationEmail({to:email,name:lastName?`${firstName} ${lastName}`:firstName,roleName:"Event Staff",token});
      res.status(201).json({success:true,message:"Staff member invited",data:{id:userId,name:lastName?`${firstName} ${lastName}`:firstName,email}});
    }catch(mailError){
      console.error("Invitation email failed to send",mailError);
      res.status(201).json({success:true,message:"Staff member created, but the invitation email could not be sent",data:{id:userId,name:lastName?`${firstName} ${lastName}`:firstName,email}});
    }
  }catch(e){fail(res,e,"Invite staff member");}
};
export const getCoOrganizers:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id);if(!id){res.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const data=await service.listCoOrganizers(organizer(res).organizerId,id);if(data===null){res.status(404).json({success:false,message:"Event not found"});return;}res.json({success:true,data});}catch(e){fail(res,e,"List co-organizers");}};
export const setCoOrganizers:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id);const rawIds=Array.isArray(req.body?.userIds)?req.body.userIds:null;const userIds=rawIds?.every((v:unknown)=>positiveInteger(v)!==null)?rawIds.map((v:unknown)=>positiveInteger(v) as number):null;if(!id||!userIds){res.status(400).json({success:false,message:"Valid event ID and staff selection are required"});return;}try{const ok=await service.setCoOrganizers(organizer(res).organizerId,organizer(res).userId,id,userIds);if(!ok){res.status(404).json({success:false,message:"Event not found"});return;}res.json({success:true,message:"Co-organizers updated"});}catch(e){if(e instanceof Error&&e.message==="INVALID_STAFF_SELECTION"){res.status(400).json({success:false,message:"All selected users must be active Event Staff members"});return;}fail(res,e,"Update co-organizers");}};
export const listVenues:RequestHandler=async(_req,res)=>{try{res.json({success:true,data:await service.listVenues()});}catch(e){fail(res,e,"List venues");}};
export const listInvitations:RequestHandler=async(_req,res)=>{try{res.json({success:true,data:await service.invitations(organizer(res).organizerId)});}catch(e){fail(res,e,"List invitations");}};
export const listNotifications:RequestHandler=async(_req,res)=>{const o=organizer(res);try{res.json({success:true,data:await service.notifications(o.userId,o.organizerId)});}catch(e){fail(res,e,"List notifications");}};
export const readNotification:RequestHandler=async(req,res)=>{const id=positiveId(req.params.id),o=organizer(res);if(!id){res.status(400).json({success:false,message:"Valid notification ID is required"});return;}try{if(!(await service.markNotification(o.userId,o.organizerId,id))){res.status(404).json({success:false,message:"Notification not found"});return;}res.json({success:true,message:"Notification marked as read"});}catch(e){fail(res,e,"Update notification");}};
export const readAllNotifications:RequestHandler=async(_req,res)=>{const o=organizer(res);try{await service.markAllNotifications(o.userId,o.organizerId);res.json({success:true,message:"All notifications marked as read"});}catch(e){fail(res,e,"Update notifications");}};
export const getReport:RequestHandler=async(req,res)=>{const eventId=req.query.eventId?(positiveInteger(req.query.eventId)??undefined):undefined,start=typeof req.query.start==="string"?req.query.start:undefined,end=typeof req.query.end==="string"?req.query.end:undefined,status=typeof req.query.status==="string"&&req.query.status!=="All"?req.query.status:undefined;try{res.json({success:true,data:await service.report(organizer(res).organizerId,eventId,start,end,status)});}catch(e){fail(res,e,"Load report");}};
export const getProfile:RequestHandler=async(_req,res)=>{try{res.json({success:true,data:await service.getProfile(organizer(res).userId)});}catch(e){fail(res,e,"Load profile");}};
export const updateProfile:RequestHandler=async(req,res)=>{const firstName=text(req.body?.firstName),organizationName=text(req.body?.organization);if(!firstName||!organizationName){res.status(400).json({success:false,message:"First name and organization are required"});return;}try{await service.updateProfile(organizer(res).userId,{firstName,organization:organizationName,lastName:optionalText(req.body?.lastName),telephone:optionalText(req.body?.telephone),position:optionalText(req.body?.position)});res.json({success:true,message:"Profile updated"});}catch(e){fail(res,e,"Update profile");}};
