import { randomBytes } from "node:crypto";
import { Router } from "express";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";

import { pool } from "../../config/database";
import { requireAdmin } from "../../middleware/require-admin";
import { optionalText, positiveId, positiveInteger, sendDatabaseError, text } from "../../utils/request";

const router=Router();router.use(requireAdmin);const statuses=new Set(["Draft","Upcoming","Active","Completed","Cancelled"]);
function slug(name:string){const base=name.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,180)||"event";return `${base}-${randomBytes(3).toString("hex")}`;}
const agendaTypes=new Set(["None","File","Url"]);
const selectEvents=`SELECT e.id,e.name,e.slug,e.theme,e.description,e.event_date AS date,DATE_FORMAT(e.event_date,'%b %e, %Y') AS dateLabel,TIME_FORMAT(e.start_time,'%H:%i') AS time,TIME_FORMAT(e.end_time,'%H:%i') AS endTime,e.timezone,e.capacity,e.status,e.image_url AS imageUrl,e.image_alt AS imageAlt,e.is_featured AS featured,e.registration_closes_at AS registrationClosesAt,e.agenda_type AS agendaType,e.agenda_url AS agendaUrl,e.agenda_file_name AS agendaFileName,e.agenda_file_type AS agendaFileType,o.id AS organizerId,o.organization AS organizer,v.id AS venueId,v.name AS venue,COUNT(r.id) AS registrations FROM events e JOIN organizers o ON o.id=e.organizer_id LEFT JOIN venues v ON v.id=e.venue_id LEFT JOIN registrations r ON r.event_id=e.id AND r.deleted_at IS NULL WHERE e.deleted_at IS NULL GROUP BY e.id,o.id,v.id`;

router.get("/",async(_request,response)=>{try{const[rows]=await pool.query<RowDataPacket[]>(`${selectEvents} ORDER BY e.event_date DESC`);response.json({success:true,data:rows});}catch(error){sendDatabaseError(response,error,"List events");}});
router.get("/:id",async(request,response)=>{const id=positiveId(request.params.id);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const[rows]=await pool.query<RowDataPacket[]>(`${selectEvents} HAVING e.id=?`,[id]);if(!rows[0]){response.status(404).json({success:false,message:"Event not found"});return;}response.json({success:true,data:rows[0]});}catch(error){sendDatabaseError(response,error,"Get event");}});

router.post("/",async(request,response)=>{const name=text(request.body?.name),organizerId=positiveInteger(request.body?.organizerId),venueId=positiveInteger(request.body?.venueId),date=text(request.body?.date),capacity=positiveInteger(request.body?.capacity),status=text(request.body?.status)||"Draft",timezone=text(request.body?.timezone)||"Africa/Nairobi",agendaType=text(request.body?.agendaType)||"None";if(!name||!organizerId||!venueId||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!capacity||!statuses.has(status)||!agendaTypes.has(agendaType)){response.status(400).json({success:false,message:"Name, organizer, venue, date, positive capacity, and valid status are required"});return;}const agendaUrl=agendaType==="None"?null:optionalText(request.body?.agendaUrl);if(agendaType!=="None"&&!agendaUrl){response.status(400).json({success:false,message:"An agenda file or URL is required when an agenda type is selected"});return;}try{const[result]=await pool.execute<ResultSetHeader>(`INSERT INTO events(organizer_id,venue_id,name,slug,theme,description,event_date,start_time,end_time,timezone,capacity,status,image_url,image_alt,is_featured,registration_closes_at,agenda_type,agenda_url,agenda_file_name,agenda_file_type)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[organizerId,venueId,name,slug(name),optionalText(request.body?.theme),optionalText(request.body?.description),date,optionalText(request.body?.startTime),optionalText(request.body?.endTime),timezone,capacity,status,optionalText(request.body?.imageUrl),optionalText(request.body?.imageAlt),Boolean(request.body?.featured),optionalText(request.body?.registrationClosesAt),agendaType,agendaUrl,agendaType==="File"?optionalText(request.body?.agendaFileName):null,agendaType==="File"?optionalText(request.body?.agendaFileType):null]);response.status(201).json({success:true,message:"Event created",id:result.insertId});}catch(error){sendDatabaseError(response,error,"Create event");}});

router.put("/:id",async(request,response)=>{const id=positiveId(request.params.id),name=text(request.body?.name),organizerId=positiveInteger(request.body?.organizerId),venueId=positiveInteger(request.body?.venueId),date=text(request.body?.date),capacity=positiveInteger(request.body?.capacity),status=text(request.body?.status),timezone=text(request.body?.timezone)||"Africa/Nairobi",agendaType=text(request.body?.agendaType)||"None";if(!id||!name||!organizerId||!venueId||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!capacity||!statuses.has(status)||!agendaTypes.has(agendaType)){response.status(400).json({success:false,message:"Valid event details are required"});return;}const agendaUrl=agendaType==="None"?null:optionalText(request.body?.agendaUrl);if(agendaType!=="None"&&!agendaUrl){response.status(400).json({success:false,message:"An agenda file or URL is required when an agenda type is selected"});return;}try{const[result]=await pool.execute<ResultSetHeader>(`UPDATE events SET organizer_id=?,venue_id=?,name=?,theme=?,description=?,event_date=?,start_time=?,end_time=?,timezone=?,capacity=?,status=?,image_url=?,image_alt=?,is_featured=?,registration_closes_at=?,agenda_type=?,agenda_url=?,agenda_file_name=?,agenda_file_type=? WHERE id=? AND deleted_at IS NULL`,[organizerId,venueId,name,optionalText(request.body?.theme),optionalText(request.body?.description),date,optionalText(request.body?.startTime),optionalText(request.body?.endTime),timezone,capacity,status,optionalText(request.body?.imageUrl),optionalText(request.body?.imageAlt),Boolean(request.body?.featured),optionalText(request.body?.registrationClosesAt),agendaType,agendaUrl,agendaType==="File"?optionalText(request.body?.agendaFileName):null,agendaType==="File"?optionalText(request.body?.agendaFileType):null,id]);if(!result.affectedRows){response.status(404).json({success:false,message:"Event not found"});return;}response.json({success:true,message:"Event updated"});}catch(error){sendDatabaseError(response,error,"Update event");}});

router.delete("/:id",async(request,response)=>{const id=positiveId(request.params.id);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const[result]=await pool.execute<ResultSetHeader>("UPDATE events SET deleted_at=CURRENT_TIMESTAMP,status='Cancelled' WHERE id=? AND deleted_at IS NULL",[id]);if(!result.affectedRows){response.status(404).json({success:false,message:"Event not found"});return;}response.json({success:true,message:"Event deleted"});}catch(error){sendDatabaseError(response,error,"Delete event");}});

export default router;
