import { randomBytes } from "node:crypto";
import { Router } from "express";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";

import { pool } from "../../config/database";
import { requireAdmin } from "../../middleware/require-admin";
import { createSetupToken, sendInvitationEmail } from "../../services/invitation.service";
import { hashPassword } from "../../utils/password";
import { optionalText, positiveId, sendDatabaseError, text } from "../../utils/request";

const router=Router(); router.use(requireAdmin); const statuses=new Set(["Active","Pending","Suspended"]);

router.get("/",async(_request,response)=>{try{const[rows]=await pool.query<RowDataPacket[]>(`SELECT o.id,u.id AS userId,CONCAT_WS(' ',p.first_name,p.last_name) AS name,p.first_name AS firstName,p.last_name AS lastName,p.email,p.telephone,o.organization,o.position,o.status,DATE_FORMAT(o.joined_at,'%b %e, %Y') AS joined,COUNT(e.id) AS eventsCreated,SUM(CASE WHEN e.status IN ('Upcoming','Active') THEN 1 ELSE 0 END) AS activeEvents FROM organizers o JOIN users u ON u.id=o.user_id JOIN people p ON p.id=u.person_id LEFT JOIN events e ON e.organizer_id=o.id AND e.deleted_at IS NULL WHERE o.deleted_at IS NULL GROUP BY o.id,u.id,p.id ORDER BY o.created_at DESC`);response.json({success:true,data:rows});}catch(error){sendDatabaseError(response,error,"List organizers");}});

router.post("/",async(request,response)=>{const firstName=text(request.body?.firstName),lastName=text(request.body?.lastName),email=text(request.body?.email).toLowerCase(),organization=text(request.body?.organization),status=text(request.body?.status)||"Pending";if(!firstName||!lastName||!email||!organization||!statuses.has(status)){response.status(400).json({success:false,message:"First name, last name, email, organization, and valid status are required"});return;}const connection=await pool.getConnection();try{await connection.beginTransaction();const[roles]=await connection.query<RowDataPacket[]>("SELECT id FROM roles WHERE name='Event Organizer' LIMIT 1");if(!roles[0])throw new Error("EVENT_ORGANIZER_ROLE_MISSING");const[person]=await connection.execute<ResultSetHeader>("INSERT INTO people(first_name,last_name,email,telephone)VALUES(?,?,?,?)",[firstName,lastName,email,optionalText(request.body?.telephone)]);const passwordHash=await hashPassword(randomBytes(32).toString("hex"));const[user]=await connection.execute<ResultSetHeader>("INSERT INTO users(person_id,password_hash,status)VALUES(?,?,'Active')",[person.insertId,passwordHash]);await connection.execute("INSERT INTO user_roles(user_id,role_id,assigned_by_user_id)VALUES(?,?,?)",[user.insertId,roles[0].id,response.locals.administrator.id]);const[organizer]=await connection.execute<ResultSetHeader>("INSERT INTO organizers(user_id,organization,position,status)VALUES(?,?,?,?)",[user.insertId,organization,optionalText(request.body?.position),status]);await connection.commit();const token=await createSetupToken(user.insertId,response.locals.administrator.id);try{await sendInvitationEmail({to:email,name:`${firstName} ${lastName}`,roleName:"Event Organizer",token});response.status(201).json({success:true,message:"Organizer created and an invitation email was sent",id:organizer.insertId});}catch(mailError){console.error("Invitation email failed to send",mailError);response.status(201).json({success:true,message:"Organizer created, but the invitation email could not be sent. Ask them to contact support.",id:organizer.insertId});}}catch(error){await connection.rollback();sendDatabaseError(response,error,"Create organizer");}finally{connection.release();}});

router.put("/:id",async(request,response)=>{const id=positiveId(request.params.id),firstName=text(request.body?.firstName),lastName=text(request.body?.lastName),email=text(request.body?.email).toLowerCase(),organization=text(request.body?.organization),status=text(request.body?.status);if(!id||!firstName||!lastName||!email||!organization||!statuses.has(status)){response.status(400).json({success:false,message:"Valid organizer details are required"});return;}const connection=await pool.getConnection();try{await connection.beginTransaction();const[rows]=await connection.query<RowDataPacket[]>("SELECT u.person_id FROM organizers o JOIN users u ON u.id=o.user_id WHERE o.id=? AND o.deleted_at IS NULL FOR UPDATE",[id]);if(!rows[0]){await connection.rollback();response.status(404).json({success:false,message:"Organizer not found"});return;}await connection.execute("UPDATE people SET first_name=?,last_name=?,email=?,telephone=? WHERE id=?",[firstName,lastName,email,optionalText(request.body?.telephone),rows[0].person_id]);await connection.execute("UPDATE organizers SET organization=?,position=?,status=? WHERE id=?",[organization,optionalText(request.body?.position),status,id]);await connection.commit();response.json({success:true,message:"Organizer updated"});}catch(error){await connection.rollback();sendDatabaseError(response,error,"Update organizer");}finally{connection.release();}});

router.delete("/:id",async(request,response)=>{const id=positiveId(request.params.id);if(!id){response.status(400).json({success:false,message:"Valid organizer ID is required"});return;}try{const[result]=await pool.execute<ResultSetHeader>("UPDATE organizers SET deleted_at=CURRENT_TIMESTAMP,status='Suspended' WHERE id=? AND deleted_at IS NULL",[id]);if(!result.affectedRows){response.status(404).json({success:false,message:"Organizer not found"});return;}response.json({success:true,message:"Organizer deleted"});}catch(error){sendDatabaseError(response,error,"Delete organizer");}});

export default router;
