import { randomBytes } from "node:crypto";
import { Router } from "express";
import type { ResultSetHeader, RowDataPacket } from "mysql2/promise";

import { pool } from "../../config/database";
import { requireAdmin } from "../../middleware/require-admin";
import { positiveId, positiveInteger, sendDatabaseError, text } from "../../utils/request";

const router=Router();router.use(requireAdmin);const statuses=new Set(["Confirmed","Pending","Cancelled"]);
router.get("/",async(_request,response)=>{try{const[rows]=await pool.query<RowDataPacket[]>(`SELECT r.id,r.reference_code AS referenceCode,CONCAT_WS(' ',p.first_name,p.last_name) AS participant,p.email,r.event_id AS eventId,e.name AS event,r.attendee_id AS attendeeId,DATE_FORMAT(r.registered_at,'%b %e, %Y') AS date,r.status,CASE WHEN ac.id IS NULL THEN 'Not Checked In' ELSE 'Checked In' END AS checkIn,ac.checked_in_at AS checkedInAt,CONCAT_WS(' ',vp.first_name,vp.last_name) AS verifiedBy,vp.email AS verifiedByEmail FROM registrations r JOIN attendees a ON a.id=r.attendee_id JOIN people p ON p.id=a.person_id JOIN events e ON e.id=r.event_id LEFT JOIN attendance_check_ins ac ON ac.registration_id=r.id LEFT JOIN users vu ON vu.id=ac.checked_in_by_user_id LEFT JOIN people vp ON vp.id=vu.person_id WHERE r.deleted_at IS NULL ORDER BY r.registered_at DESC`);response.json({success:true,data:rows});}catch(error){sendDatabaseError(response,error,"List registrations");}});
router.get("/:id/scan-log",async(request,response)=>{const id=positiveId(request.params.id);if(!id){response.status(400).json({success:false,message:"Valid registration ID is required"});return;}try{const[rows]=await pool.query<RowDataPacket[]>(`SELECT sl.id,sl.scan_method AS scanMethod,sl.result,sl.scanned_at AS scannedAt,CONCAT_WS(' ',sp.first_name,sp.last_name) AS scannedBy,sp.email AS scannedByEmail FROM attendance_scan_logs sl LEFT JOIN users su ON su.id=sl.scanned_by_user_id LEFT JOIN people sp ON sp.id=su.person_id WHERE sl.registration_id=? ORDER BY sl.scanned_at DESC`,[id]);response.json({success:true,data:rows});}catch(error){sendDatabaseError(response,error,"List scan log");}});
router.post("/",async(request,response)=>{const eventId=positiveInteger(request.body?.eventId),attendeeId=positiveInteger(request.body?.attendeeId),status=text(request.body?.status)||"Pending";if(!eventId||!attendeeId||!statuses.has(status)){response.status(400).json({success:false,message:"Event, attendee, and valid status are required"});return;}const referenceCode=`REG-${Date.now().toString(36).toUpperCase()}-${randomBytes(2).toString("hex").toUpperCase()}`,ticketToken=randomBytes(32).toString("hex");try{const[result]=await pool.execute<ResultSetHeader>("INSERT INTO registrations(reference_code,ticket_token,event_id,attendee_id,status)VALUES(?,?,?,?,?)",[referenceCode,ticketToken,eventId,attendeeId,status]);response.status(201).json({success:true,message:"Registration created",id:result.insertId});}catch(error){sendDatabaseError(response,error,"Create registration");}});
router.put("/:id",async(request,response)=>{const id=positiveId(request.params.id),status=text(request.body?.status),checkIn=text(request.body?.checkIn);if(!id||!statuses.has(status)||!["Checked In","Not Checked In"].includes(checkIn)){response.status(400).json({success:false,message:"Valid registration status and check-in state are required"});return;}const connection=await pool.getConnection();try{await connection.beginTransaction();const[result]=await connection.execute<ResultSetHeader>("UPDATE registrations SET status=?,cancelled_at=CASE WHEN ?='Cancelled' THEN CURRENT_TIMESTAMP ELSE NULL END WHERE id=? AND deleted_at IS NULL",[status,status,id]);if(!result.affectedRows){await connection.rollback();response.status(404).json({success:false,message:"Registration not found"});return;}if(checkIn==="Checked In")await connection.execute("INSERT INTO attendance_check_ins(registration_id,checked_in_by_user_id)VALUES(?,?) ON DUPLICATE KEY UPDATE checked_in_by_user_id=VALUES(checked_in_by_user_id),checked_in_at=CURRENT_TIMESTAMP",[id,response.locals.administrator.id]);else await connection.execute("DELETE FROM attendance_check_ins WHERE registration_id=?",[id]);await connection.commit();response.json({success:true,message:"Registration updated"});}catch(error){await connection.rollback();sendDatabaseError(response,error,"Update registration");}finally{connection.release();}});
router.delete("/:id",async(request,response)=>{const id=positiveId(request.params.id);if(!id){response.status(400).json({success:false,message:"Valid registration ID is required"});return;}try{const[result]=await pool.execute<ResultSetHeader>("UPDATE registrations SET deleted_at=CURRENT_TIMESTAMP,status='Cancelled',cancelled_at=CURRENT_TIMESTAMP WHERE id=? AND deleted_at IS NULL",[id]);if(!result.affectedRows){response.status(404).json({success:false,message:"Registration not found"});return;}response.json({success:true,message:"Registration deleted"});}catch(error){sendDatabaseError(response,error,"Delete registration");}});
export default router;
