import { randomBytes } from "node:crypto";
import type { ResultSetHeader,RowDataPacket } from "mysql2/promise";
import { pool } from "../../config/database";
import { hashPassword } from "../../utils/password";

export type StaffInvite={firstName:string;lastName?:string|null;email:string;telephone?:string|null};

export type EventInput={name:string;venueId:number;theme?:string|null;description?:string|null;date:string;startTime?:string|null;endTime?:string|null;timezone:string;capacity:number;status:string;imageUrl?:string|null;imageAlt?:string|null;registrationClosesAt?:string|null;agendaType?:string;agendaUrl?:string|null;agendaFileName?:string|null;agendaFileType?:string|null};
export type ScheduleInput={eventId:number;speakerId?:number|null;title:string;description?:string|null;date:string;startTime:string;endTime?:string|null;room?:string|null;sortOrder:number};
export type SpeakerInput={eventId:number;firstName:string;lastName?:string|null;email:string;telephone?:string|null;title:string;organization?:string|null;bio?:string|null;photoUrl?:string|null;type:string;status:string};
const eventSelect=`SELECT e.id,e.name,e.slug,e.theme,e.description,DATE_FORMAT(e.event_date,'%Y-%m-%d') date,DATE_FORMAT(e.event_date,'%b %e, %Y') dateLabel,TIME_FORMAT(e.start_time,'%H:%i') time,TIME_FORMAT(e.end_time,'%H:%i') endTime,e.timezone,e.capacity,e.status,e.image_url imageUrl,e.image_alt imageAlt,e.registration_closes_at registrationClosesAt,e.agenda_type agendaType,e.agenda_url agendaUrl,e.agenda_file_name agendaFileName,e.agenda_file_type agendaFileType,v.id venueId,v.name venue,COUNT(r.id) registrations FROM events e LEFT JOIN venues v ON v.id=e.venue_id LEFT JOIN registrations r ON r.event_id=e.id AND r.deleted_at IS NULL WHERE e.deleted_at IS NULL AND e.organizer_id=?`;
const eventGroup=` GROUP BY e.id,v.id`;
function slug(name:string){const base=name.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,180)||"event";return `${base}-${randomBytes(3).toString("hex")}`;}
async function ownsEvent(organizerId:number,eventId:number){const[rows]=await pool.query<RowDataPacket[]>("SELECT 1 FROM events WHERE id=? AND organizer_id=? AND deleted_at IS NULL",[eventId,organizerId]);return rows.length>0;}

export async function dashboard(organizerId:number){const[[stats],[statuses],[upcoming]]=await Promise.all([
  pool.query<RowDataPacket[]>(`SELECT COUNT(DISTINCT e.id) totalEvents,COUNT(DISTINCT CASE WHEN e.status='Upcoming' THEN e.id END) upcomingEvents,COUNT(DISTINCT r.id) totalRegistrations,COUNT(DISTINCT r.attendee_id) totalAttendees,COUNT(DISTINCT CASE WHEN e.event_date=CURDATE() THEN e.id END) eventsToday,ROUND(100*COUNT(DISTINCT ac.id)/NULLIF(COUNT(DISTINCT CASE WHEN r.status='Confirmed' THEN r.id END),0),1) averageAttendance FROM events e LEFT JOIN registrations r ON r.event_id=e.id AND r.deleted_at IS NULL LEFT JOIN attendance_check_ins ac ON ac.registration_id=r.id WHERE e.organizer_id=? AND e.deleted_at IS NULL`,[organizerId]),
  pool.query<RowDataPacket[]>("SELECT status,COUNT(*) value FROM events WHERE organizer_id=? AND deleted_at IS NULL GROUP BY status",[organizerId]),
  pool.query<RowDataPacket[]>(`${eventSelect} AND e.event_date>=CURDATE()${eventGroup} ORDER BY e.event_date,e.start_time LIMIT 6`,[organizerId]),
]);return{stats:stats[0]??{},statuses,upcoming};}
export async function registrationTrends(organizerId:number,days:number){const[rows]=await pool.query<RowDataPacket[]>(`SELECT DATE_FORMAT(r.registered_at,'%Y-%m-%d') day,COUNT(*) value FROM registrations r JOIN events e ON e.id=r.event_id WHERE e.organizer_id=? AND e.deleted_at IS NULL AND r.deleted_at IS NULL AND r.registered_at>=DATE_SUB(CURDATE(),INTERVAL ? DAY) GROUP BY DATE(r.registered_at) ORDER BY DATE(r.registered_at)`,[organizerId,days-1]);const map=new Map(rows.map(r=>[r.day,Number(r.value)]));return Array.from({length:days},(_,index)=>{const date=new Date();date.setHours(12,0,0,0);date.setDate(date.getDate()-(days-1-index));const key=date.toISOString().slice(0,10);return{date:key,label:date.toLocaleDateString("en-US",{month:"short",day:"numeric"}),value:map.get(key)??0};});}
export async function listEvents(organizerId:number){const[rows]=await pool.query<RowDataPacket[]>(`${eventSelect}${eventGroup} ORDER BY e.event_date DESC`,[organizerId]);return rows;}
export async function getEvent(organizerId:number,id:number){const[rows]=await pool.query<RowDataPacket[]>(`${eventSelect} AND e.id=?${eventGroup}`,[organizerId,id]);return rows[0]??null;}
export async function createEvent(organizerId:number,input:EventInput){const[result]=await pool.execute<ResultSetHeader>(`INSERT INTO events(organizer_id,venue_id,name,slug,theme,description,event_date,start_time,end_time,timezone,capacity,status,image_url,image_alt,registration_closes_at,agenda_type,agenda_url,agenda_file_name,agenda_file_type)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,[organizerId,input.venueId,input.name,slug(input.name),input.theme??null,input.description??null,input.date,input.startTime??null,input.endTime??null,input.timezone,input.capacity,input.status,input.imageUrl??null,input.imageAlt??null,input.registrationClosesAt??null,input.agendaType??"None",input.agendaUrl??null,input.agendaFileName??null,input.agendaFileType??null]);return result.insertId;}
export async function updateEvent(organizerId:number,id:number,input:EventInput){const[result]=await pool.execute<ResultSetHeader>(`UPDATE events SET venue_id=?,name=?,theme=?,description=?,event_date=?,start_time=?,end_time=?,timezone=?,capacity=?,status=?,image_url=?,image_alt=?,registration_closes_at=?,agenda_type=?,agenda_url=?,agenda_file_name=?,agenda_file_type=? WHERE id=? AND organizer_id=? AND deleted_at IS NULL`,[input.venueId,input.name,input.theme??null,input.description??null,input.date,input.startTime??null,input.endTime??null,input.timezone,input.capacity,input.status,input.imageUrl??null,input.imageAlt??null,input.registrationClosesAt??null,input.agendaType??"None",input.agendaUrl??null,input.agendaFileName??null,input.agendaFileType??null,id,organizerId]);return result.affectedRows>0;}
export async function cancelEvent(organizerId:number,id:number){const[result]=await pool.execute<ResultSetHeader>("UPDATE events SET status='Cancelled' WHERE id=? AND organizer_id=? AND deleted_at IS NULL",[id,organizerId]);return result.affectedRows>0;}

export async function listRegistrations(organizerId:number,eventId?:number){const values:any[]=[organizerId];let extra="";if(eventId){extra=" AND e.id=?";values.push(eventId);}const[rows]=await pool.query<RowDataPacket[]>(`SELECT r.id,r.reference_code referenceCode,CONCAT_WS(' ',p.first_name,p.last_name) attendee,p.email,r.event_id eventId,e.name event,DATE_FORMAT(r.registered_at,'%b %e, %Y') registeredAt,r.status,CASE WHEN ac.id IS NULL THEN 'Not Checked In' ELSE 'Checked In' END checkIn FROM registrations r JOIN events e ON e.id=r.event_id JOIN attendees a ON a.id=r.attendee_id JOIN people p ON p.id=a.person_id LEFT JOIN attendance_check_ins ac ON ac.registration_id=r.id WHERE e.organizer_id=? AND e.deleted_at IS NULL AND r.deleted_at IS NULL${extra} ORDER BY r.registered_at DESC`,values);return rows;}
export async function updateRegistrationStatus(organizerId:number,id:number,status:string){const[result]=await pool.execute<ResultSetHeader>(`UPDATE registrations r JOIN events e ON e.id=r.event_id SET r.status=?,r.cancelled_at=CASE WHEN ?='Cancelled' THEN CURRENT_TIMESTAMP ELSE NULL END WHERE r.id=? AND e.organizer_id=? AND e.deleted_at IS NULL AND r.deleted_at IS NULL`,[status,status,id,organizerId]);return result.affectedRows>0;}
export async function checkInRegistration(organizerId:number,userId:number,id:number,checkedIn:boolean){const connection=await pool.getConnection();try{await connection.beginTransaction();const[rows]=await connection.query<RowDataPacket[]>("SELECT r.id FROM registrations r JOIN events e ON e.id=r.event_id WHERE r.id=? AND e.organizer_id=? AND e.deleted_at IS NULL AND r.deleted_at IS NULL FOR UPDATE",[id,organizerId]);if(!rows[0]){await connection.rollback();return false;}if(checkedIn)await connection.execute("INSERT INTO attendance_check_ins(registration_id,checked_in_by_user_id)VALUES(?,?) ON DUPLICATE KEY UPDATE checked_in_by_user_id=VALUES(checked_in_by_user_id),checked_in_at=CURRENT_TIMESTAMP",[id,userId]);else await connection.execute("DELETE FROM attendance_check_ins WHERE registration_id=?",[id]);await connection.commit();return true;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
export async function listAttendees(organizerId:number,eventId?:number){const values:any[]=[organizerId];let extra="";if(eventId){extra=" AND e.id=?";values.push(eventId);}const[rows]=await pool.query<RowDataPacket[]>(`SELECT a.id,CONCAT_WS(' ',p.first_name,p.last_name) name,p.email,p.telephone,COUNT(DISTINCT r.event_id) eventsRegistered,GROUP_CONCAT(DISTINCT e.name ORDER BY e.name SEPARATOR ', ') events,GROUP_CONCAT(DISTINCT e.id) eventIds,DATE_FORMAT(MAX(r.registered_at),'%b %e, %Y') lastRegistration,COUNT(DISTINCT ac.id) attendance FROM attendees a JOIN people p ON p.id=a.person_id JOIN registrations r ON r.attendee_id=a.id AND r.deleted_at IS NULL JOIN events e ON e.id=r.event_id AND e.organizer_id=? AND e.deleted_at IS NULL LEFT JOIN attendance_check_ins ac ON ac.registration_id=r.id WHERE a.deleted_at IS NULL${extra} GROUP BY a.id,p.id ORDER BY MAX(r.registered_at) DESC`,values);return rows;}

export async function listSchedule(organizerId:number,eventId?:number){const values:any[]=[organizerId];let extra="";if(eventId){extra=" AND e.id=?";values.push(eventId);}const[rows]=await pool.query<RowDataPacket[]>(`SELECT s.id,s.event_id eventId,e.name event,s.speaker_id speakerId,CONCAT_WS(' ',p.first_name,p.last_name) speaker,s.title,s.description,DATE_FORMAT(s.item_date,'%Y-%m-%d') date,TIME_FORMAT(s.start_time,'%H:%i') startTime,TIME_FORMAT(s.end_time,'%H:%i') endTime,s.room,s.sort_order sortOrder,s.created_by_role createdByRole,CONCAT_WS(' ',cp.first_name,cp.last_name) createdBy FROM event_schedule_items s JOIN events e ON e.id=s.event_id LEFT JOIN speakers sp ON sp.id=s.speaker_id LEFT JOIN people p ON p.id=sp.person_id LEFT JOIN users cu ON cu.id=s.created_by_user_id LEFT JOIN people cp ON cp.id=cu.person_id WHERE e.organizer_id=? AND e.deleted_at IS NULL AND s.deleted_at IS NULL${extra} ORDER BY s.item_date,s.start_time,s.sort_order`,values);return rows;}
export async function createSchedule(organizerId:number,userId:number,input:ScheduleInput){if(!(await ownsEvent(organizerId,input.eventId)))return null;if(input.speakerId){const[assignment]=await pool.query<RowDataPacket[]>("SELECT 1 FROM event_speakers WHERE event_id=? AND speaker_id=?",[input.eventId,input.speakerId]);if(!assignment[0])throw new Error("SPEAKER_NOT_ASSIGNED");}const[result]=await pool.execute<ResultSetHeader>("INSERT INTO event_schedule_items(event_id,speaker_id,title,description,item_date,start_time,end_time,room,sort_order,created_by_user_id,created_by_role)VALUES(?,?,?,?,?,?,?,?,?,?,'Organizer')",[input.eventId,input.speakerId??null,input.title,input.description??null,input.date,input.startTime,input.endTime??null,input.room??null,input.sortOrder,userId]);return result.insertId;}
export async function updateSchedule(organizerId:number,id:number,input:ScheduleInput){if(!(await ownsEvent(organizerId,input.eventId)))return false;const[result]=await pool.execute<ResultSetHeader>(`UPDATE event_schedule_items s JOIN events e ON e.id=s.event_id SET s.event_id=?,s.speaker_id=?,s.title=?,s.description=?,s.item_date=?,s.start_time=?,s.end_time=?,s.room=?,s.sort_order=? WHERE s.id=? AND e.organizer_id=? AND s.deleted_at IS NULL`,[input.eventId,input.speakerId??null,input.title,input.description??null,input.date,input.startTime,input.endTime??null,input.room??null,input.sortOrder,id,organizerId]);return result.affectedRows>0;}
export async function deleteSchedule(organizerId:number,id:number){const[result]=await pool.execute<ResultSetHeader>(`UPDATE event_schedule_items s JOIN events e ON e.id=s.event_id SET s.deleted_at=CURRENT_TIMESTAMP WHERE s.id=? AND e.organizer_id=? AND s.deleted_at IS NULL`,[id,organizerId]);return result.affectedRows>0;}

export async function listSpeakers(organizerId:number,eventId?:number){const values:any[]=[organizerId];let extra="";if(eventId){extra=" AND e.id=?";values.push(eventId);}const[rows]=await pool.query<RowDataPacket[]>(`SELECT sp.id,es.event_id eventId,e.name event,CONCAT_WS(' ',p.first_name,p.last_name) name,p.first_name firstName,p.last_name lastName,p.email,p.telephone,sp.professional_title title,sp.organization,sp.bio,sp.photo_url photoUrl,sp.speaker_type type,es.invitation_status status FROM event_speakers es JOIN events e ON e.id=es.event_id JOIN speakers sp ON sp.id=es.speaker_id AND sp.deleted_at IS NULL JOIN people p ON p.id=sp.person_id WHERE e.organizer_id=? AND e.deleted_at IS NULL${extra} ORDER BY sp.created_at DESC`,values);return rows;}
export async function createSpeaker(organizerId:number,input:SpeakerInput){if(!(await ownsEvent(organizerId,input.eventId)))return null;const connection=await pool.getConnection();try{await connection.beginTransaction();const[person]=await connection.execute<ResultSetHeader>("INSERT INTO people(first_name,last_name,email,telephone)VALUES(?,?,?,?)",[input.firstName,input.lastName??null,input.email,input.telephone??null]);const[speaker]=await connection.execute<ResultSetHeader>("INSERT INTO speakers(person_id,professional_title,organization,bio,photo_url,speaker_type)VALUES(?,?,?,?,?,?)",[person.insertId,input.title,input.organization??null,input.bio??null,input.photoUrl??null,input.type]);await connection.execute("INSERT INTO event_speakers(event_id,speaker_id,invitation_status,confirmed_at)VALUES(?,?,?,CASE WHEN ?='Confirmed' THEN CURRENT_TIMESTAMP ELSE NULL END)",[input.eventId,speaker.insertId,input.status,input.status]);await connection.commit();return speaker.insertId;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
export async function updateSpeaker(organizerId:number,id:number,input:SpeakerInput){if(!(await ownsEvent(organizerId,input.eventId)))return false;const connection=await pool.getConnection();try{await connection.beginTransaction();const[rows]=await connection.query<RowDataPacket[]>("SELECT sp.person_id FROM speakers sp JOIN event_speakers es ON es.speaker_id=sp.id JOIN events e ON e.id=es.event_id WHERE sp.id=? AND es.event_id=? AND e.organizer_id=? FOR UPDATE",[id,input.eventId,organizerId]);if(!rows[0]){await connection.rollback();return false;}await connection.execute("UPDATE people SET first_name=?,last_name=?,email=?,telephone=? WHERE id=?",[input.firstName,input.lastName??null,input.email,input.telephone??null,rows[0].person_id]);await connection.execute("UPDATE speakers SET professional_title=?,organization=?,bio=?,photo_url=?,speaker_type=? WHERE id=?",[input.title,input.organization??null,input.bio??null,input.photoUrl??null,input.type,id]);await connection.execute("UPDATE event_speakers SET invitation_status=?,confirmed_at=CASE WHEN ?='Confirmed' THEN CURRENT_TIMESTAMP ELSE NULL END WHERE event_id=? AND speaker_id=?",[input.status,input.status,input.eventId,id]);await connection.commit();return true;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
export async function deleteSpeaker(organizerId:number,eventId:number,id:number){const connection=await pool.getConnection();try{await connection.beginTransaction();const[result]=await connection.execute<ResultSetHeader>("DELETE es FROM event_speakers es JOIN events e ON e.id=es.event_id WHERE es.event_id=? AND es.speaker_id=? AND e.organizer_id=?",[eventId,id,organizerId]);if(!result.affectedRows){await connection.rollback();return false;}const[remaining]=await connection.query<RowDataPacket[]>("SELECT 1 FROM event_speakers WHERE speaker_id=? LIMIT 1",[id]);if(!remaining[0])await connection.execute("UPDATE speakers SET deleted_at=CURRENT_TIMESTAMP WHERE id=?",[id]);await connection.commit();return true;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}

export async function inviteStaff(invitedByUserId:number,input:StaffInvite):Promise<number>{
  const connection=await pool.getConnection();
  try{
    await connection.beginTransaction();
    const[roleRows]=await connection.query<RowDataPacket[]>("SELECT id FROM roles WHERE slug='event-staff' LIMIT 1");
    const role=roleRows[0];if(!role)throw new Error("ROLE_MISSING");
    const[person]=await connection.execute<ResultSetHeader>("INSERT INTO people(first_name,last_name,email,telephone)VALUES(?,?,?,?)",[input.firstName,input.lastName??null,input.email,input.telephone??null]);
    const placeholderHash=await hashPassword(randomBytes(32).toString("hex"));
    const[user]=await connection.execute<ResultSetHeader>("INSERT INTO users(person_id,password_hash,status)VALUES(?,?,'Active')",[person.insertId,placeholderHash]);
    await connection.execute("INSERT INTO user_roles(user_id,role_id,assigned_by_user_id)VALUES(?,?,?)",[user.insertId,role.id,invitedByUserId]);
    await connection.commit();
    return user.insertId;
  }catch(error){await connection.rollback();throw error;}finally{connection.release();}
}

export async function listStaffOptions(){const[rows]=await pool.query<RowDataPacket[]>(`SELECT u.id,CONCAT_WS(' ',p.first_name,p.last_name) name,p.email,p.telephone,u.status,DATE_FORMAT(u.created_at,'%b %e, %Y') joined,DATE_FORMAT(u.last_active_at,'%b %e, %Y') lastActive,EXISTS(SELECT 1 FROM account_setup_tokens t WHERE t.user_id=u.id AND t.used_at IS NULL AND t.expires_at>CURRENT_TIMESTAMP) setupPending,COUNT(DISTINCT es.event_id) assignedEvents FROM users u JOIN people p ON p.id=u.person_id JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id LEFT JOIN event_staff es ON es.user_id=u.id WHERE r.slug='event-staff' AND u.status='Active' AND u.deleted_at IS NULL GROUP BY u.id ORDER BY name`);return rows;}
export async function listCoOrganizers(organizerId:number,eventId:number){if(!(await ownsEvent(organizerId,eventId)))return null;const[rows]=await pool.query<RowDataPacket[]>(`SELECT es.user_id userId,CONCAT_WS(' ',p.first_name,p.last_name) name,p.email,es.assignment_role assignmentRole,es.assigned_at assignedAt FROM event_staff es JOIN users u ON u.id=es.user_id JOIN people p ON p.id=u.person_id WHERE es.event_id=? ORDER BY name`,[eventId]);return rows;}
export async function setCoOrganizers(organizerId:number,assignedByUserId:number,eventId:number,userIds:number[]){if(!(await ownsEvent(organizerId,eventId)))return false;const connection=await pool.getConnection();try{await connection.beginTransaction();if(userIds.length){const[valid]=await connection.query<RowDataPacket[]>(`SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE r.slug='event-staff' AND u.id IN (${userIds.map(()=>"?").join(",")})`,userIds);if(valid.length!==new Set(userIds).size){throw new Error("INVALID_STAFF_SELECTION");}}await connection.execute("DELETE FROM event_staff WHERE event_id=?",[eventId]);for(const userId of userIds){await connection.execute("INSERT INTO event_staff(event_id,user_id,assignment_role,assigned_by_user_id)VALUES(?,?,?,?)",[eventId,userId,"co_organizer",assignedByUserId]);}await connection.commit();return true;}catch(error){await connection.rollback();throw error;}finally{connection.release();}}

export async function listVenues(){const[rows]=await pool.query<RowDataPacket[]>("SELECT id,name,address location,capacity,description,contact,status FROM venues WHERE deleted_at IS NULL AND status IN ('Available','Active') ORDER BY name");return rows;}
export async function invitations(organizerId:number){const[rows]=await pool.query<RowDataPacket[]>("SELECT id,name,slug,status,registration_closes_at registrationClosesAt,event_date eventDate FROM events WHERE organizer_id=? AND deleted_at IS NULL ORDER BY event_date DESC",[organizerId]);return rows;}
export async function notifications(userId:number,organizerId:number){const[rows]=await pool.query<RowDataPacket[]>(`SELECT n.id,n.notification_type type,n.title,n.message,n.is_read isRead,n.created_at createdAt,e.name event FROM notifications n LEFT JOIN events e ON e.id=n.related_event_id WHERE n.recipient_user_id=? AND (n.related_event_id IS NULL OR e.organizer_id=?) ORDER BY n.created_at DESC`,[userId,organizerId]);return rows;}
export async function markNotification(userId:number,organizerId:number,id:number){const[result]=await pool.execute<ResultSetHeader>(`UPDATE notifications n LEFT JOIN events e ON e.id=n.related_event_id SET n.is_read=TRUE,n.read_at=CURRENT_TIMESTAMP WHERE n.id=? AND n.recipient_user_id=? AND (n.related_event_id IS NULL OR e.organizer_id=?)`,[id,userId,organizerId]);return result.affectedRows>0;}
export async function markAllNotifications(userId:number,organizerId:number){await pool.execute(`UPDATE notifications n LEFT JOIN events e ON e.id=n.related_event_id SET n.is_read=TRUE,n.read_at=COALESCE(n.read_at,CURRENT_TIMESTAMP) WHERE n.recipient_user_id=? AND n.is_read=FALSE AND (n.related_event_id IS NULL OR e.organizer_id=?)`,[userId,organizerId]);}
export async function report(organizerId:number,eventId?:number,start?:string,end?:string,status?:string){const values:any[]=[organizerId];let where="";if(eventId){where+=" AND e.id=?";values.push(eventId);}if(start){where+=" AND e.event_date>=?";values.push(start);}if(end){where+=" AND e.event_date<=?";values.push(end);}if(status){where+=" AND e.status=?";values.push(status);}const[byEvent]=await pool.query<RowDataPacket[]>(`SELECT e.id,e.name,e.status,DATE_FORMAT(e.event_date,'%Y-%m-%d') date,COUNT(DISTINCT r.id) registrations,COUNT(DISTINCT ac.id) attendance FROM events e LEFT JOIN registrations r ON r.event_id=e.id AND r.deleted_at IS NULL LEFT JOIN attendance_check_ins ac ON ac.registration_id=r.id WHERE e.organizer_id=? AND e.deleted_at IS NULL${where} GROUP BY e.id ORDER BY e.event_date`,values);const[trend]=await pool.query<RowDataPacket[]>(`SELECT DATE_FORMAT(r.registered_at,'%Y-%m-%d') date,COUNT(DISTINCT r.id) registrations,COUNT(DISTINCT ac.id) attendance FROM registrations r JOIN events e ON e.id=r.event_id LEFT JOIN attendance_check_ins ac ON ac.registration_id=r.id WHERE e.organizer_id=? AND e.deleted_at IS NULL AND r.deleted_at IS NULL${where} GROUP BY DATE(r.registered_at) ORDER BY DATE(r.registered_at)`,values);return{byEvent,trend};}
export async function getProfile(userId:number){const[rows]=await pool.query<RowDataPacket[]>("SELECT u.id,CONCAT_WS(' ',p.first_name,p.last_name) name,p.first_name firstName,p.last_name lastName,p.email,p.telephone,o.organization,o.position FROM users u JOIN people p ON p.id=u.person_id JOIN organizers o ON o.user_id=u.id WHERE u.id=? AND o.deleted_at IS NULL",[userId]);return rows[0]??null;}
export async function updateProfile(userId:number,input:{firstName:string;lastName?:string|null;telephone?:string|null;organization:string;position?:string|null}){const connection=await pool.getConnection();try{await connection.beginTransaction();await connection.execute("UPDATE people p JOIN users u ON u.person_id=p.id SET p.first_name=?,p.last_name=?,p.telephone=? WHERE u.id=?",[input.firstName,input.lastName??null,input.telephone??null,userId]);await connection.execute("UPDATE organizers SET organization=?,position=? WHERE user_id=? AND deleted_at IS NULL",[input.organization,input.position??null,userId]);await connection.commit();}catch(error){await connection.rollback();throw error;}finally{connection.release();}}
