import { Router } from "express";

import { databaseErrorCode } from "../config/database";
import { requireDiscussionUser, type DiscussionIdentity } from "../middleware/require-discussion-user";
import * as discussions from "../services/discussion.service";

const router = Router();
router.use(requireDiscussionUser);
const user = (locals: Record<string, unknown>) => locals.discussionUser as DiscussionIdentity;
const eventId = (value: string | string[] | undefined) => { const id = Number(value); return Number.isSafeInteger(id) && id > 0 ? id : null; };
const fail = (response: import("express").Response, error: unknown, action: string) => { console.error(`${action} failed (${databaseErrorCode(error)})`); response.status(503).json({ success: false, message: `Unable to ${action.toLowerCase()}` }); };

router.get("/", async (_request, response) => { try { response.json({ success: true, data: await discussions.listDiscussions(user(response.locals)) }); } catch (error) { fail(response, error, "List discussions"); } });
router.get("/:eventId", async (request, response) => { const id=eventId(request.params.eventId); if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;} try{const data=await discussions.getDiscussion(id,user(response.locals));if(!data){response.status(403).json({success:false,message:"You do not have access to this event discussion"});return;}response.json({success:true,data});}catch(error){fail(response,error,"Load discussion");} });
router.get("/:eventId/messages", async (request,response)=>{const id=eventId(request.params.eventId);const after=Math.max(0,Number(request.query.afterId)||0);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const data=await discussions.listMessages(id,user(response.locals),after);if(!data){response.status(403).json({success:false,message:"You do not have access to this event discussion"});return;}response.json({success:true,data});}catch(error){fail(response,error,"Load messages");}});
router.post("/:eventId/messages",async(request,response)=>{const id=eventId(request.params.eventId);const message=typeof request.body?.message==="string"?request.body.message.trim():"";if(!id||!message||message.length>2000){response.status(400).json({success:false,message:"A message between 1 and 2000 characters is required"});return;}try{const result=await discussions.sendMessage(id,user(response.locals),message);if(result.kind==="forbidden"){response.status(403).json({success:false,message:"You do not have access to this event discussion"});return;}if(result.kind==="closed"){response.status(409).json({success:false,message:"This discussion is closed"});return;}response.status(201).json({success:true,data:{id:result.id},message:"Message sent"});}catch(error){fail(response,error,"Send message");}});
router.post("/:eventId/open",async(request,response)=>{const id=eventId(request.params.eventId);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{if(!(await discussions.setDiscussionStatus(id,user(response.locals),"Open"))){response.status(403).json({success:false,message:"The discussion can only be opened by an authorized manager from 20 minutes before the event"});return;}response.json({success:true,message:"Discussion opened"});}catch(error){fail(response,error,"Open discussion");}});
router.post("/:eventId/close",async(request,response)=>{const id=eventId(request.params.eventId);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{if(!(await discussions.setDiscussionStatus(id,user(response.locals),"Closed"))){response.status(403).json({success:false,message:"You are not authorized to close this discussion at this time"});return;}response.json({success:true,message:"Discussion closed"});}catch(error){fail(response,error,"Close discussion");}});
router.post("/:eventId/typing",async(request,response)=>{const id=eventId(request.params.eventId);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{if(!(await discussions.markTyping(id,user(response.locals)))){response.status(409).json({success:false,message:"Typing is unavailable for this discussion"});return;}response.status(204).end();}catch(error){fail(response,error,"Update typing status");}});
router.get("/:eventId/typing",async(request,response)=>{const id=eventId(request.params.eventId);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const data=await discussions.listTyping(id,user(response.locals));if(data===null){response.status(403).json({success:false,message:"You do not have access to this event discussion"});return;}response.json({success:true,data});}catch(error){fail(response,error,"Load typing status");}});
router.get("/:eventId/participants",async(request,response)=>{const id=eventId(request.params.eventId);if(!id){response.status(400).json({success:false,message:"Valid event ID is required"});return;}try{const data=await discussions.listParticipants(id,user(response.locals));if(data===null){response.status(403).json({success:false,message:"Administrator access is required"});return;}response.json({success:true,data});}catch(error){fail(response,error,"Load discussion participants");}});
router.delete("/:eventId/participants/:userId",async(request,response)=>{const id=eventId(request.params.eventId);const target=eventId(request.params.userId);if(!id||!target){response.status(400).json({success:false,message:"Valid event and user IDs are required"});return;}try{if(!(await discussions.removeParticipant(id,target,user(response.locals)))){response.status(403).json({success:false,message:"Only a confirmed attendee can be removed by an administrator"});return;}response.json({success:true,message:"Attendee removed from the discussion"});}catch(error){fail(response,error,"Remove discussion participant");}});

export default router;
