-- Participant journey / secure ticket patch.
-- Additive only: preserves every existing registration and check-in.
USE event_management_system;
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE registrations
  ADD COLUMN IF NOT EXISTS ticket_token CHAR(64) NULL DEFAULT NULL AFTER reference_code;

CREATE UNIQUE INDEX uq_registrations_ticket_token
  ON registrations (ticket_token);

-- Backfill opaque tokens for existing active registrations. UUID values contain
-- no attendee information and are sufficient for legacy rows; all new tickets
-- use 256-bit cryptographically random tokens generated by Node.js.
UPDATE registrations
SET ticket_token = REPLACE(CONCAT(UUID(), UUID()), '-', '')
WHERE ticket_token IS NULL;

ALTER TABLE registrations
  MODIFY COLUMN ticket_token CHAR(64) NOT NULL;
