import { Router } from "express";
import * as controller from "../../controllers/organizer/organizer.controller";
import { requireOrganizer } from "../../middleware/require-organizer";
import { uploadEventAgenda,uploadEventImage } from "../admin/uploads.routes";
const router=Router();router.use(requireOrganizer);
router.get("/dashboard",controller.getDashboard);router.get("/dashboard/registration-trends",controller.getTrends);
router.get("/events",controller.listEvents);router.post("/events",controller.createEvent);router.get("/events/:id",controller.getEvent);router.put("/events/:id",controller.updateEvent);router.patch("/events/:id/cancel",controller.cancelEvent);
router.get("/staff-options",controller.listStaffOptions);router.post("/staff-options",controller.inviteStaff);router.get("/events/:id/co-organizers",controller.getCoOrganizers);router.put("/events/:id/co-organizers",controller.setCoOrganizers);
router.get("/registrations",controller.listRegistrations);router.patch("/registrations/:id/status",controller.updateRegistration);
router.get("/attendees",controller.listAttendees);
router.get("/schedule",controller.listSchedule);router.post("/schedule",controller.createSchedule);router.put("/schedule/:id",controller.updateSchedule);router.delete("/schedule/:id",controller.deleteSchedule);
router.get("/speakers",controller.listSpeakers);router.post("/speakers",controller.createSpeaker);router.put("/speakers/:id",controller.updateSpeaker);router.delete("/speakers/:id",controller.deleteSpeaker);
router.get("/venues",controller.listVenues);router.get("/invitations",controller.listInvitations);
router.get("/notifications",controller.listNotifications);router.patch("/notifications/read-all",controller.readAllNotifications);router.patch("/notifications/:id/read",controller.readNotification);
router.get("/reports",controller.getReport);router.get("/profile",controller.getProfile);router.put("/profile",controller.updateProfile);
router.post("/uploads/event-image",uploadEventImage);router.post("/uploads/event-agenda",uploadEventAgenda);
export default router;
